export const mapTypes = {
	SET_MAP: "SET_MAP",
	SET_REGION: "SET_REGION",
	TOGGLE_LABEL: "TOGGLE_LABEL",
	SET_FONT: "SET_FONT",
	SET_FONT_SIZE: "SET_FONT_SIZE",
	SET_POSITION: "SET_POSITION",
	SET_TEXT: "SET_TEXT",
	SET_FILL: "SET_FILL",
	SET_BORDER: "SET_BORDER",
	SET_PROPERTY: "SET_PROPERTY",
	SET_LEGEND: "SET_LEGEND",
};