export const MenuTypes = {
	NONE: "",
	FINALIZE_DROP_DOWN: "FINALIZE_DROP_DOWN",
	FINALIZE_COLOR: "FINALIZE_COLOR",
	SET_POSITION: "SET_POSITION",
	SET_FONT: "SET_FONT",
	SET_FILL: "SET_FILL",
	SET_BORDER: "SET_BORDER",
	SET_PROPERTY: "SET_PROPERTY",
};