export const ModalTypes = {
	NONE: "NONE",
	UPLOAD_MAP: "UPLOAD_MAP",
	CHOOSE_TEMPLATE: "CHOOSE_TEMPLATE",
	SET_DATA: "SET_DATA",
	SET_TEXT: "SET_TEXT",
	EDIT_LEGEND: "EDIT_LEGEND",
	ADD_LAYER: "ADD_LAYER",
	PUBLISH_MAP: "PUBLISH_MAP",
	DELETE_MAP: "DELETE_MAP",
	RENAME_MAP: "RENAME_MAP",
	FORK_MAP: "FORK_MAP",
	SET_TAGS: "SET_TAGS"
};