name: Backend Tests

on:
  workflow_call

jobs:
  jest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: make tests envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          directory: tests/backend
          envkey_DB_CONNECT: ${{ secrets.DB_CONNECT }}
          envkey_CLIENT_URL: ${{ vars.DEV_CLIENT_URL }}
          envkey_ENVIRONMENT: ${{ vars.TEST_ENVIRONMENT }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_EMAIL_USER: ${{ secrets.EMAIL_USER }}
          envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          envkey_REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          envkey_S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          envkey_S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          envkey_S3_REGION: ${{ secrets.S3_REGION }}

      - name: jest run
        run: 'cd server && npm ci && cd ../tests/backend && npm ci && npm test'
