name: Run App Deploy

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  # We want the unit tests to pass first before we deploy the backend first.
  # We want to deploy the backend first because if it is successful and the front end fails, the user will still have a old version of a front end that works instead of a frontend that have new features that doesn't work without the server.

  # aws-server-deploy:
  #   uses: ./.github/workflows/aws-server-deploy.yml
  #   secrets: inherit
  #   needs: unit-tests
  
  
  vercel-client-deploy:
    uses: ./.github/workflows/vercel-client-deploy.yml
    secrets: inherit
    # needs: [aws-server-deploy]