name: Unit Tests

on:
  workflow_call

jobs:
  run-frontend-tests:
    uses: ./.github/workflows/frontend-tests.yml
    secrets: inherit

  run-backend-tests:
    uses: ./.github/workflows/backend-tests.yml
    secrets: inherit